


logging:
  level:
    com.liupeng.sell.mapper: debug

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://119.23.187.80:3306/sell?characterEncoding=utf-8&useSSL=false
    #jpa
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 119.23.187.80
    port: 6379
# 又拍云服务 见 https://console.upyun.com/services/file/
upyun:
  bucketName: XXX
  userName: xxx
  password: xxxx
  imageHost: http://xxx.com/